"""add WeddingTable model and Guest.table_id

Revision ID: 6e76c3626f47
Revises: 32317c6c89f4
Create Date: 2026-03-25 14:42:42.152229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e76c3626f47'
down_revision = '32317c6c89f4'
branch_labels = None
depends_on = None


def upgrade():
    # Create wedding_tables if it doesn't already exist (partial migration recovery)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'wedding_tables' not in existing_tables:
        op.create_table('wedding_tables',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wedding_id', sa.Integer(), nullable=False),
        sa.Column('table_number', sa.Integer(), nullable=False),
        sa.Column('table_name', sa.String(length=100), nullable=True),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('shape', sa.String(length=20), nullable=False),
        sa.Column('position_x', sa.Float(), nullable=True),
        sa.Column('position_y', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('wedding_tables', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_wedding_tables_wedding_id'), ['wedding_id'], unique=False)

    # Add table_id to guests if not already present
    guest_cols = [c['name'] for c in inspector.get_columns('guests')]
    if 'table_id' not in guest_cols:
        with op.batch_alter_table('guests', schema=None) as batch_op:
            batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_guests_table_id'), ['table_id'], unique=False)
            batch_op.create_foreign_key('fk_guests_table_id', 'wedding_tables', ['table_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_guests_table_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_guests_table_id'))
        batch_op.drop_column('table_id')

    with op.batch_alter_table('wedding_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wedding_tables_wedding_id'))

    op.drop_table('wedding_tables')
    # ### end Alembic commands ###
