"""Add Vendor model and vendor_id to Expense

Revision ID: 32317c6c89f4
Revises: 6aea3ee4af32
Create Date: 2026-03-25 13:17:48.598561

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "32317c6c89f4"
down_revision = "6aea3ee4af32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wedding_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("quoted_price", sa.Float(), nullable=True),
        sa.Column("deposit_amount", sa.Float(), nullable=True),
        sa.Column("deposit_paid", sa.Boolean(), nullable=False),
        sa.Column("deposit_due_date", sa.Date(), nullable=True),
        sa.Column("contracted", sa.Boolean(), nullable=False),
        sa.Column("contract_signed_date", sa.Date(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wedding_id"],
            ["weddings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vendors_wedding_id"), ["wedding_id"], unique=False)

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("vendor_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_expenses_vendor_id"), ["vendor_id"], unique=False)
        batch_op.create_foreign_key(None, "vendors", ["vendor_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_expenses_vendor_id"))
        batch_op.drop_column("vendor_id")

    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vendors_wedding_id"))

    op.drop_table("vendors")
    # ### end Alembic commands ###
