"""Add contract_url to vendor

Revision ID: 42b1c5398bcd
Revises: 7ca08c6b7724
Create Date: 2026-04-17 19:56:06.162829

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "42b1c5398bcd"
down_revision = "7ca08c6b7724"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("contract_url", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.drop_column("contract_url")

    # ### end Alembic commands ###
