"""Add user profile fields

Revision ID: 4f5a78e3e9ac
Revises: 6e76c3626f47
Create Date: 2026-03-26 12:15:21.675946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5a78e3e9ac'
down_revision = '6e76c3626f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_color', sa.String(length=7), nullable=False, server_default='#c9687a'))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('timezone')
        batch_op.drop_column('phone')
        batch_op.drop_column('avatar_color')

    # ### end Alembic commands ###
