"""Add final payment fields to vendor

Revision ID: 7ca08c6b7724
Revises: f1eb36a7e4f5
Create Date: 2026-04-16 19:00:06.224030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca08c6b7724'
down_revision = 'f1eb36a7e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_payment_paid', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('final_payment_due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('final_payment_due_date')
        batch_op.drop_column('final_payment_paid')
        batch_op.drop_column('final_payment_amount')

    # ### end Alembic commands ###
