"""Add ChecklistItem model

Revision ID: a6b422fa4c93
Revises:
Create Date: 2026-03-25 12:48:44.124861

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a6b422fa4c93"
down_revision = "b8e32f1d9000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wedding_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wedding_id"],
            ["weddings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checklist_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_checklist_items_wedding_id"), ["wedding_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checklist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checklist_items_wedding_id"))

    op.drop_table("checklist_items")
    # ### end Alembic commands ###
