"""Add rsvp_contact to Wedding

Revision ID: f1eb36a7e4f5
Revises: 4f5a78e3e9ac
Create Date: 2026-03-26 20:00:31.975732

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f1eb36a7e4f5"
down_revision = "4f5a78e3e9ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rsvp_contact", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weddings", schema=None) as batch_op:
        batch_op.drop_column("rsvp_contact")

    # ### end Alembic commands ###
